stages:
  - build
  - release

build for Linux amd64:
  stage: build
  image: golang
  script:
    - GOOS=linux GOARCH=amd64 go build -o env main.go
  artifacts:
    paths:
      - env

build for Windows amd64:
  stage: build
  image: golang
  script:
    - GOOS=windows GOARCH=amd64 go build -o env.exe main.go
  artifacts:
    paths:
      - env.exe

upload artifacts:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - 'curl -H "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file env ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/env/${CI_COMMIT_TAG}/env'
    - 'curl -H "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file env.exe ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/env/${CI_COMMIT_TAG}/env.exe'

release artifacts:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script: echo "Running release step"
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: $CI_COMMIT_TAG
    description: "Release ${CI_COMMIT_TAG} of env"