name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/checkout@v2.3.4
    
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        
      - name: Build for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build ./cmd/env
        
      - name: Build for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build ./cmd/env
